"use strict";

module.exports = Object.freeze({
  APP_GET_INFO: "app:get-info",
  LOCALES_LIST: "locales:list",
  RUNTIME_GET_STATUS: "runtime:get-status",
  RUNTIME_INSTALL: "runtime:install",
  RUNTIME_CANCEL_INSTALL: "runtime:cancel-install",
  RUNTIME_EVENT: "runtime:event",
  MODELS_LIST: "models:list",
  MODELS_GET_DIAGNOSTICS: "models:get-diagnostics",
  GENERATION_START: "generation:start",
  GENERATION_CANCEL: "generation:cancel",
  GENERATION_EVENT: "generation:event",
  QUEUE_GET_STATE: "queue:get-state",
  QUEUE_CANCEL_ALL: "queue:cancel-all",
  QUEUE_REMOVE: "queue:remove",
  QUEUE_MOVE: "queue:move",
  QUEUE_CLEAR_FINISHED: "queue:clear-finished",
  QUEUE_REVEAL_RESULT: "queue:reveal-result",
  QUEUE_TRASH_RESULT: "queue:trash-result",
  QUEUE_EVENT: "queue:event",
  MODELS_DIAGNOSE: "models:diagnose",
  MODELS_OPEN_FOLDER: "models:open-folder",
  SUPPORT_ASSETS_GET_STATUS: "support-assets:get-status",
  SUPPORT_ASSETS_INSTALL: "support-assets:install",
  SUPPORT_ASSETS_EVENT: "support-assets:event",
  REFINE_SELECT_IMAGE: "refine:select-image",
  REFINE_ADD_DROPPED_IMAGE: "refine:add-dropped-image",
  PRESETS_LIST: "presets:list",
  PRESETS_READ: "presets:read",
  PRESETS_SAVE: "presets:save",
  PRESETS_TRASH: "presets:trash",
  PRESETS_OPEN_FOLDER: "presets:open-folder",
});
